version: '2'
services:

  # Laravel Restful Service
  app:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # Thrift
  thrift:
    build:
      context: ./
      dockerfile: thrift.dockerfile
    working_dir: /microservices
    volumes:
      - ./microservice:/microservices
    ports:
      - 9090:9090
    command: "python ./demo/demo_rpc.py"

  # Flask Restful Service
  # flask-service:
  #   build: ./flask  # path is relative to docker-compose.yml location
  #   volumes:
  #     - ./app:/usr/src/flask # mount point
  #   ports:
  #     - 5000:5000  # host:container

  # The Database
  # database:
  #   image: mysql:5.6
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     - "MYSQL_DATABASE=homestead"
  #     - "MYSQL_USER=homestead"
  #     - "MYSQL_PASSWORD=secret"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   ports:
  #       - "33061:3306"

volumes:
  dbdata:
