version: '3'
services:

  # Laravel Restful Service
  laravel-service:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80

  # Thrift
  thrift:
    build:
      context: ./
      dockerfile: thrift.dockerfile
    working_dir: /microservices
    volumes:
      - ./microservices:/microservices
    ports:
      - 9090:9090
    # Runs each of the micro services and maybe deals with a toggle
    # thats where ansible comes in 
    # command: "thrift -help"
    # command: "thrift --gen php microservices/rpc.thrift && thrift --gen py:utf8strings ./microservices/rpc.thrift"
    # command: "thrift --gen php rpc.thrift && thrift --gen py:utf8strings rpc.thrift"
    # $ docker run -v "$PWD:/data" thrift thrift -o /data --gen rb /data/service.thrift

  # Flask Restful Service
  # flask-service:
  #   build: 
  #     context: ./  # path is relative to docker-compose.yml location
      # dockerfile: flask.dockerfile
  #   volumes:
  #     - ./app:/usr/src/flask # mount point
  #   ports:
  #     - 5000:5000  # host:container

  # The Database
  # database:
  #   image: mysql:5.6
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     - "MYSQL_DATABASE=homestead"
  #     - "MYSQL_USER=homestead"
  #     - "MYSQL_PASSWORD=secret"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   ports:
  #       - "33061:3306"

volumes:
  laravel-service:
